services:
  mysql:
    image: mysql
    ports:
      - "3308:3306"
    expose:
      - "3308"
    networks:
      - producer_net
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=taskmaster
      - MYSQL_ROOT_PASSWORD=123
networks:
  producer_net:
    driver: bridge
